language: java

os:
        - linux
        - osx

jdk:
        - openjdk11
env:
  - MAVEN_VERSION=3.6.3

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION} -Dhttps.protocols=TLSv1.2"
